In [1]:
import torch
# mac gpu
device = torch.device("mps")

In [2]:
X = torch.arange(12, device=device)
X

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], device='mps:0')

In [3]:
Y = torch.arange(12)
Y

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
Y = Y.to(device)
Y

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], device='mps:0')

In [11]:
import pandas as pd
import numpy as np
data = pd.read_csv('./Data/house_tiny.csv')
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [17]:
inputs = data.iloc[:, 0:2]
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs = inputs.fillna(inputs.mean()).astype(np.float32)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0         1.0        0.0
1       2.0         0.0        1.0
2       4.0         0.0        1.0
3       3.0         0.0        1.0

In [18]:
x = torch.tensor(inputs.values)
x

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]])

In [20]:
x = x.to(device)
x

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], device='mps:0')