In [1]:
import numpy as np
import pandas as pd
import torch
# gpu版本 发现会崩
device = torch.device('mps')

In [2]:
# 一般运算
x = torch.tensor([3.0]).to(device)
y = torch.tensor([2.0]).to(device)
x + y, x - y, x * y, x / y

(tensor([5.], device='mps:0'),
 tensor([1.], device='mps:0'),
 tensor([6.], device='mps:0'),
 tensor([1.5000], device='mps:0'))

In [2]:
# 对称矩阵
A = torch.tensor([[1., 2, 3], [5, 6, 7], [9, 10, 11]])
A == A.T

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

In [7]:
# 元素求和
X = torch.arange(24).reshape(2, 3, 4).to(dtype=torch.float)
X.sum()

tensor(276.)

In [8]:
X.sum(axis=0)

tensor([[12., 14., 16., 18.],
        [20., 22., 24., 26.],
        [28., 30., 32., 34.]])

In [10]:
X.sum(axis=[0,1])

tensor([60., 66., 72., 78.])

In [6]:
# 均值，个数
X.mean(), X.numel()

(tensor(11.5000), 24)

In [7]:
# 向量点积 torch.dot
r = torch.dot(x, y)
r

tensor(6., device='mps:0')

In [8]:
# 矩阵向量相乘 torch.mv ???
a = torch.ones(3, 1).to(device)
A @ a

tensor([[ 6.],
        [18.],
        [30.]], device='mps:0')

In [4]:
# 矩阵相乘 torch.mm
B = torch.arange(12).reshape(3, -1).to(dtype=torch.float)
torch.mm(A, B)

tensor([[ 32.,  38.,  44.,  50.],
        [ 80.,  98., 116., 134.],
        [128., 158., 188., 218.]])

In [5]:
# L2范数 torch.norm
A.norm()

tensor(20.6398)

In [6]:
# L1范数 torch.abs().sum()
torch.abs(A).sum()

tensor(54.)