In [1]:
import numpy as np
import pandas as pd
import torch

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True) # 存储梯度即倒数
x.grad

In [4]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
# 在默认情况下，PyTorch会累积梯度，计算新的前需清除
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [10]:
x.grad.zero_()
y = x * x
u = y.detach() # detach 将 u 变为常量
z = u * x

z.sum().backward()
u == x.grad

tensor([True, True, True, True])