In [1]:
import torch
from torch import nn
from d2l import torch as d2l

### 汇聚层/池化层实现

In [5]:
def pool2d(X, pool_size, mode='max'):
    h, w = pool_size
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i, j] = X[i:i + h, j:j + w].max()
            elif mode == 'mean':
                Y[i, j] = X[i:i + h, j:j + w].mean()
    return Y

In [7]:
X = torch.arange(12.).reshape(3, -1)
pool2d(X, (2,2), 'max')

tensor([[ 5.,  6.,  7.],
        [ 9., 10., 11.]])

In [8]:
pool2d(X, (2, 2), 'mean')

tensor([[2.5000, 3.5000, 4.5000],
        [6.5000, 7.5000, 8.5000]])

### 填充和步幅

In [15]:
X = X.reshape(1, 1, 3, 4).cuda()
# padding 填充  stride 步幅
pool2d = nn.MaxPool2d(2, padding=0, stride=1).cuda()
pool2d(X)

tensor([[[[ 5.,  6.,  7.],
          [ 9., 10., 11.]]]], device='cuda:0')

### 多通道输入

In [16]:
X = torch.cat((X, X+1), 1)
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.]]]], device='cuda:0')

In [25]:
pool2d = nn.MaxPool2d(3, padding=1, stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [ 9., 11.]],

         [[ 6.,  8.],
          [10., 12.]]]], device='cuda:0')